### ISSUE TITLE
Keep me Signed-In (omitDeviceToken) is not working

### ISSUE THREAD

**Issue by susheelrbusireddy** [okta/okta-idx-swift#133] opened 2023-04-07 13:54 UTC
### Describe the bug?

When a user selects "Remember Device", we are passing omitDeviceToken as FALSE, but user is challenged with MFA for every subsequent login.
 
<img width="972" alt="Screenshot 2023-04-05 at 2 40 36 PM" src="https://user-images.githubusercontent.com/58010360/230618887-d933f274-605e-4a33-9cbb-37f4791afe04.png">

<img width="895" alt="Screenshot 2023-04-05 at 2 42 12 PM" src="https://user-images.githubusercontent.com/58010360/230619129-2e6b604c-f34f-421c-8b2f-dc8c1da549f1.png">

<img width="1181" alt="Screenshot 2023-04-05 at 2 43 08 PM" src="https://user-images.githubusercontent.com/58010360/230619306-2092ba43-20c5-4e86-83bb-65d9a3168e50.png">

### What is expected to happen?

User should not be challenged with MFA for subsequent login based on Authentication/Global Session policy

### What is the actual behavior?

User is challenged with MFA for every login whether omitDeviceToken is TRUE or FALSE

### Reproduction Steps?

1. Start authentication
2. Select Remember Me(Keep me Signed-In)
3. Pass omitDeviceToken as FALSE
4. Complete authentication
5. Logout and login again

### SDK Version(s)

3.0.7

**Comment by mikenachbaur-okta** [comment] 2023-04-11 00:57
@susheelrbusireddy Have you tested it without passing the `.omitDeviceToken` option at all?  I've tested locally, and either excluding that option, or supplying `false`, results in the DT cookie being set either way.

Alternatively, can you ensure the DT cookie is being included in the outbound requests?  You can do that by trying one of the following:
1. Use a proxy to intercept the API calls
2. Set a breakpoint in [APIClient.swift, line 176](https://github.com/okta/okta-mobile-swift/blob/master/Sources/AuthFoundation/Network/APIClient.swift#L176) to inspect the request before it is sent over the network
3. Add yourself as a network delegate and intercept the network requests and/or their responses, to see what their results were.  You can use `flow.client.add(delegate:)`, and implement one of the [APIClientDelegate methods](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/apiclientdelegate), (the [api(client:didSend:received:)](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/apiclientdelegate/api(client:didsend:received:)-4ob1d) method is probably your best bet there).

**Comment by mikenachbaur-okta** [comment] 2023-07-07 15:12
Since I haven't been able to reproduce the issue, I'm going to close it. If you're still experiencing this, please feel free to reopen the ticket.

**Closed by mikenachbaur-okta** 2023-07-07 15:12 UTC
Labels: bug
